# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Okkur - Syna"
theme = "syna"
enableGitInfo = true
version = "0.17.2"
DefaultContentLanguage = "en"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Okkur Labs"
  description = "Open Source Theme for your next project"
  DefaultContentLanguage = "en"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

[languages]
  [languages.en]
    title = "English title"
    weight = 1
    [[languages.en.menu.main]]
      url = "/"
      name = "Home"
      weight = 10
    [[languages.en.menu.main]]
      url = "/about"
      name = "About Us"
      weight = 20
    [[languages.en.menu.main]]
      url = "#contact"
      name = "Contact"
      weight = 30
    [[languages.en.menu.footer]]
      url = "#"
      name = "Link"
      weight = 10
    [[languages.en.menu.footer]]
      url = "#"
      name = "Long Link"
      weight = 30
    [[languages.en.menu.footer]]
      url = "#"
      name = "Tiny Link"
      weight = 30
    [[languages.en.menu.copyright_footer]]
      url = "/about"
      name = "About Us"
      weight = 10
    [[languages.en.menu.copyright_footer]]
      url = "#"
      name = "Another Link"
      weight = 30
    [[languages.en.menu.footer_social]]
      weight = 20
      name = "facebook"
      pre = "fab fa-facebook-f"
      url = "#"
    [[languages.en.menu.footer_social]]
      weight = 30
      name = "linkedin"
      pre = "fab fa-linkedin-in"
      url = "#"

  [languages.de]
    title = "Deutscher Titel"
    weight = 2
    [[languages.de.menu.main]]
      url = "/"
      name = "Zuhause"
      weight = 10
    [[languages.de.menu.main]]
      url = "/about"
      name = "Über uns"
      weight = 20
    [[languages.de.menu.main]]
      url = "#contact"
      name = "Kontakt"
      weight = 30
    [[languages.de.menu.footer]]
      url = "#"
      name = "Link"
      weight = 10
    [[languages.de.menu.footer]]
      url = "#"
      name = "Langer Link"
      weight = 30
    [[languages.de.menu.footer]]
      url = "#"
      name = "Winziger Link"
      weight = 30
    [[languages.de.menu.copyright_footer]]
      url = "/about"
      name = "Über uns"
      weight = 10
    [[languages.de.menu.copyright_footer]]
      url = "#"
      name = "Anderer Link"
      weight = 30
    [[languages.de.menu.footer_social]]
      weight = 20
      name = "facebook"
      pre = "fab fa-facebook-f"
      url = "#"
    [[languages.de.menu.footer_social]]
      weight = 30
      name = "linkedin"
      pre = "fab fa-linkedin-in"
      url = "#"
